name: AlerteOpening_Workflows

on:
  schedule:
    - cron: '*/5 * * * *'  # toutes les 5 minutes
  workflow_dispatch:      # permet de lancer manuellement

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Lancer le script d'alerte
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python src/AlerteOpening.py
