name: AlerteOpening_Workflows

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Installation de Tor
      - name: Install Tor and Socks
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
          python -m pip install --upgrade pip
          pip install requests[socks] pandas pytz  # Ou pip install -r requirements.txt

      # Lancement de Tor
      - name: Start Tor Service
        run: |
          sudo service tor start
          # Attente obligatoire pour que le circuit Tor soit prÃªt
          sleep 15

      - name: Lancer le script d'alerte
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python src/AlerteOpening.py

      - name: Commit et push data.json (forcÃ©)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          git diff --staged --quiet && git commit --allow-empty -m "ðŸ¤– Tor Run [$TIMESTAMP]" || git commit -m "ðŸ¤– Mise Ã  jour data.json [$TIMESTAMP]"
          git push