name: AlerteOpening_Workflows

on:
  schedule:
    - cron: '*/5 * * * *'  # toutes les 5 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt

      # --- 1️⃣ Télécharger le data.json du dernier run ---
      - name: Télécharger artifact précédent
        uses: actions/download-artifact@v3
        with:
          name: data-json
          path: .

      # --- 2️⃣ Lancer le script ---
      - name: Lancer le script d'alerte
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DATA_FILE: data.json
        run: python src/AlerteOpening.py

      # --- 3️⃣ Uploader le data.json mis à jour ---
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-json
          path: data.json
